src: .\images\model.ply
dest: ''
operations:
- 1
1:
  type: rotate
  mode: Degree
  x: 0.0
  y: 0.0
  z: 0.0

2:
  type: clear
  height: 0.0
  mode: Below 

4:
  type: move
  x: 0.0
  y: 0.0
  z: 0.0
     
