src: .\images\model.ply
dest: ''
operations:
- 1
1:
  type: rotate
  mode: Degree
  x: 0.0
  y: 0.0
  z: 0.0

2:
  type: clear
  height: 0.0
  mode: Below

3:
  type: crop_by_cycle
  crop_rx: 0.0
  crop_lx: 0.0
  crop_fy: 0.0
  crop_by: 0.0

4:
  type: crop_by_box
  crop_rx: 0.0
  crop_lx: 0.0
  crop_fy: 0.0
  crop_by: 0.0

5:
  type: mount
  picture_path: path

6:
  type: move
  x: 0.0
  y: 0.0
  z: 0.0